### ISSUE TITLE
Documentation on how Tags work

### ISSUE THREAD

**Issue by SasLuca** [files-community/Website#106]
### What's the Problem?

Tags are a very nice feature, however without documentation on how they are stored and clarifications regarding how they work when operations are done on files outside of Files, it can be too risky for power users to get invested into the system because they could risk losing the tag data or not being able to migrate/sync it to another system in the future.

### Solution/Idea

A documentation page that explains how Tags are stored, their limitations, what happens if files are modified outside of Files.
Ideally, a link to the documentation could be added to the UI of Files next to the settings menu for tags (maybe as an info button) in order to help with the discoverability of these details.

### Alternatives

Not sure what an alternative would be here

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by paddirn** [comment]
Just came here to make a similar comment, though also I would ask if there's any way to apply tags throughout a folder's contents? Not sure if it's a setting that I missed, but currently if you apply a tag to a folder, nothing inside of that folder gains the tags. Potentially it's by design to not slow things down, but it'd be nice if tagging a folder also propagated that same tag to it's contents. Also, there should probably be an easier way to  add new tags, the only way I'm seeing is by editing some code in a text file.

**Comment by yaira2** [comment]
Documentation on the tags feature is now available.
