### ISSUE TITLE
The same margin are not set to table on docs

### ISSUE THREAD

**Issue by onein528** [files-community/Website#190]
### Before you start...

- [X] Have you refreshed the page? You might be using an old version of the site.
- [X] Have you checked for an existing issue on this topic? If there is one, post a comment on it instead.

### What browsers are you seeing the problem on?

Chrome

### Description

![image](https://user-images.githubusercontent.com/62196528/160290427-1133d619-a1df-4c3a-93ce-2ab14dce2154.png)

### Steps To Reproduce

1. go to https://files.community/docs/configuring/custom-themes

Maybe need to change the table style. (im not familiar with svelte :<)

### Expected behavior

Same margin/padding

**Comment by etidart** [comment]
Hey! I just looked at it. The problem here is the table's fixed width. On my local machine, I fixed this issue by setting the table width to be dependent on the screen width and adding a horizontal scrollbar below it. I think this is a good solution. I'll make a PR right now.
![screenshot](https://user-images.githubusercontent.com/53515110/166467988-04ffdbfb-1b9b-4c8e-9f4c-c636e1bcb53c.png)

**Comment by onein528** [comment]
@etidart Thank you.
