### ISSUE TITLE
Website Translation

### ISSUE THREAD

**Issue by Gr1ZzLy23** [files-community/Website#40]
Hello guys, your website is only available in English and I want to translate it into my native Georgian and use it as my default language. I think that many Georgians will be happy with such news on your official website and many will use it and easily understand everything.

**Comment by onein528** [comment]
Japanese too.

**Comment by cinqmilleans** [comment]
I think translating this website will greatly increase adoption. Personally, I would love to send the url of the web page to people I know, but I don't because it's in English. And the site gives much more desire than the microsoft store.

@TheOnlyTails @yaichenbaum Is the source code of the site available?

**Comment by TheOnlyTails** [comment]
it- you're quite literally in the source code's repo 😅

**Comment by yaira2** [comment]
Can we use Crowdin for this?

**Comment by TheOnlyTails** [comment]
Hi everyone, we're nearing the merging of this feature, so this is the time to request any locales you'd like to translate ahead of time, so we could avoid making too much PRs after merging.

**Comment by yaira2** [comment]
Translation should be done through Crowdin, I added the top 30 localizations but can add more if requested. https://crowdin.com/project/files-website

**Comment by yaira2** [comment]
Might be a good idea to add this link to the readme
